// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: /Users/tomascalle/Documents/GitHub/Analizador/src/Analizador/lexer.flex

package Analizador;
import java.util.ArrayList;
import java_cup.runtime.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\22\0\1\3\1\4\1\5"+
    "\3\0\1\6\1\0\1\7\1\10\2\11\1\12\1\11"+
    "\1\13\1\11\12\14\1\15\1\16\1\17\1\20\1\17"+
    "\2\0\1\21\1\22\1\23\1\24\1\25\1\26\1\22"+
    "\1\27\1\30\2\22\1\31\1\32\1\33\1\34\1\35"+
    "\1\22\1\36\1\37\1\40\6\22\4\0\1\41\1\0"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\2\22\1\53\1\54\1\55\1\56\2\22\1\57"+
    "\1\60\1\61\1\62\5\22\1\0\1\6\10\0\1\2"+
    "\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\15\16"+
    "\1\14\1\0\16\16\1\17\2\16\1\11\27\16\1\0"+
    "\6\16\1\20\2\16\1\21\1\22\1\16\1\23\1\16"+
    "\1\24\1\0\5\16\1\0\4\16\1\25\1\26\1\27"+
    "\3\16\1\30\4\16\1\0\13\16\1\0\1\16\1\31"+
    "\6\16\1\32\1\33\1\16\1\0\2\16\1\34\1\35"+
    "\1\36\2\16\1\0\2\16\1\37\1\16\1\0\2\16"+
    "\1\40\1\0\1\41\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\63\0\146\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\231\0\63\0\63\0\146\0\146\0\314"+
    "\0\377\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\63\0\u0363\0\u0396\0\u03c9"+
    "\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\63"+
    "\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e"+
    "\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6"+
    "\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\314\0\u0cf3"+
    "\0\u0d26\0\314\0\314\0\u0d59\0\314\0\u0d8c\0\314\0\u0dbf"+
    "\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57"+
    "\0\u0f8a\0\u0fbd\0\314\0\314\0\314\0\u0ff0\0\u1023\0\u1056"+
    "\0\314\0\u1089\0\u10bc\0\u10ef\0\u1122\0\u1155\0\u1188\0\u11bb"+
    "\0\u11ee\0\u1221\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353"+
    "\0\u1386\0\u13b9\0\u13ec\0\314\0\u141f\0\u1452\0\u1485\0\u14b8"+
    "\0\u14eb\0\u151e\0\314\0\314\0\u1551\0\u1584\0\u15b7\0\u15ea"+
    "\0\314\0\314\0\314\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9"+
    "\0\314\0\u171c\0\u174f\0\u1782\0\u17b5\0\314\0\u17e8\0\314"+
    "\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\3\20\1\21\1\22\1\23\1\24\1\20\1\25"+
    "\1\26\2\20\1\27\1\30\1\31\1\20\1\2\5\20"+
    "\1\32\1\20\1\33\2\20\1\34\6\20\103\0\1\35"+
    "\55\0\1\36\1\13\62\0\1\20\4\0\42\20\14\0"+
    "\1\20\4\0\25\20\1\37\14\20\14\0\1\20\4\0"+
    "\34\20\1\40\2\20\1\41\2\20\14\0\1\20\4\0"+
    "\7\20\1\42\21\20\1\43\10\20\14\0\1\20\4\0"+
    "\1\44\20\20\1\45\20\20\14\0\1\20\4\0\25\20"+
    "\1\46\14\20\14\0\1\20\4\0\7\20\1\47\21\20"+
    "\1\50\10\20\14\0\1\20\4\0\21\20\1\51\14\20"+
    "\1\52\3\20\14\0\1\20\4\0\25\20\1\53\14\20"+
    "\14\0\1\20\4\0\25\20\1\54\3\20\1\55\10\20"+
    "\14\0\1\20\4\0\31\20\1\56\10\20\14\0\1\20"+
    "\4\0\21\20\1\57\20\20\14\0\1\20\4\0\31\20"+
    "\1\50\10\20\14\0\1\60\62\0\1\20\4\0\13\20"+
    "\1\61\26\20\14\0\1\20\4\0\40\20\1\62\1\20"+
    "\14\0\1\20\4\0\23\20\1\63\16\20\14\0\1\20"+
    "\4\0\12\20\1\64\27\20\14\0\1\20\4\0\34\20"+
    "\1\65\5\20\14\0\1\20\4\0\2\20\1\66\37\20"+
    "\14\0\1\20\4\0\23\20\1\67\13\20\1\70\2\20"+
    "\14\0\1\20\4\0\25\20\1\71\14\20\14\0\1\20"+
    "\4\0\4\20\1\72\35\20\14\0\1\20\4\0\25\20"+
    "\1\73\14\20\14\0\1\20\4\0\36\20\1\74\1\75"+
    "\2\20\14\0\1\20\4\0\35\20\1\76\4\20\14\0"+
    "\1\20\4\0\21\20\1\77\20\20\14\0\1\20\4\0"+
    "\27\20\1\100\12\20\14\0\1\20\4\0\34\20\1\101"+
    "\5\20\14\0\1\20\4\0\34\20\1\102\5\20\14\0"+
    "\1\20\4\0\23\20\1\67\16\20\14\0\1\20\4\0"+
    "\40\20\1\103\1\20\14\0\1\20\4\0\25\20\1\104"+
    "\7\20\1\105\4\20\14\0\1\20\4\0\36\20\1\106"+
    "\3\20\14\0\1\20\4\0\11\20\1\107\30\20\3\0"+
    "\1\110\10\0\1\20\4\0\11\20\1\111\2\20\1\112"+
    "\1\20\1\113\23\20\14\0\1\20\4\0\4\20\1\114"+
    "\35\20\14\0\1\20\4\0\25\20\1\115\14\20\14\0"+
    "\1\20\4\0\40\20\1\116\1\20\14\0\1\20\4\0"+
    "\36\20\1\117\3\20\14\0\1\20\4\0\12\20\1\120"+
    "\27\20\14\0\1\20\4\0\34\20\1\121\5\20\14\0"+
    "\1\20\4\0\21\20\1\122\20\20\14\0\1\20\4\0"+
    "\35\20\1\123\4\20\14\0\1\20\4\0\27\20\1\124"+
    "\12\20\14\0\1\20\4\0\32\20\1\125\7\20\14\0"+
    "\1\20\4\0\41\20\1\126\14\0\1\20\4\0\35\20"+
    "\1\127\4\20\3\0\1\130\10\0\1\20\4\0\33\20"+
    "\1\111\6\20\14\0\1\20\4\0\36\20\1\131\3\20"+
    "\14\0\1\20\4\0\36\20\1\132\3\20\14\0\1\20"+
    "\4\0\34\20\1\133\5\20\14\0\1\20\4\0\31\20"+
    "\1\134\10\20\14\0\1\20\4\0\7\20\1\135\32\20"+
    "\32\0\1\136\44\0\1\20\4\0\31\20\1\137\10\20"+
    "\14\0\1\20\4\0\21\20\1\140\14\20\1\141\3\20"+
    "\14\0\1\20\4\0\25\20\1\142\3\20\1\143\10\20"+
    "\14\0\1\20\4\0\15\20\1\144\24\20\14\0\1\20"+
    "\4\0\36\20\1\144\3\20\14\0\1\20\4\0\21\20"+
    "\1\145\20\20\14\0\1\20\4\0\17\20\1\146\22\20"+
    "\14\0\1\20\4\0\40\20\1\147\1\20\14\0\1\20"+
    "\4\0\36\20\1\150\3\20\14\0\1\20\4\0\34\20"+
    "\1\151\5\20\54\0\1\136\22\0\1\20\4\0\35\20"+
    "\1\152\4\20\14\0\1\20\4\0\35\20\1\125\4\20"+
    "\14\0\1\20\4\0\23\20\1\153\16\20\14\0\1\20"+
    "\4\0\22\20\1\154\17\20\14\0\1\20\4\0\4\20"+
    "\1\155\35\20\52\0\1\156\24\0\1\20\4\0\25\20"+
    "\1\157\14\20\14\0\1\20\4\0\36\20\1\160\3\20"+
    "\14\0\1\20\4\0\35\20\1\161\4\20\14\0\1\20"+
    "\4\0\27\20\1\162\12\20\14\0\1\20\4\0\15\20"+
    "\1\163\24\20\14\0\1\20\4\0\36\20\1\164\3\20"+
    "\14\0\1\20\4\0\21\20\1\165\20\20\14\0\1\20"+
    "\4\0\11\20\1\166\30\20\14\0\1\20\4\0\25\20"+
    "\1\167\14\20\14\0\1\20\4\0\31\20\1\170\10\20"+
    "\14\0\1\20\4\0\12\20\1\171\27\20\46\0\1\172"+
    "\30\0\1\20\4\0\34\20\1\173\5\20\14\0\1\20"+
    "\4\0\21\20\1\174\20\20\14\0\1\20\4\0\27\20"+
    "\1\175\12\20\14\0\1\20\4\0\41\20\1\176\14\0"+
    "\1\20\4\0\1\177\41\20\14\0\1\20\4\0\21\20"+
    "\1\200\20\20\14\0\1\20\4\0\33\20\1\201\6\20"+
    "\14\0\1\20\4\0\35\20\1\202\4\20\14\0\1\20"+
    "\4\0\37\20\1\203\2\20\14\0\1\20\4\0\36\20"+
    "\1\204\3\20\14\0\1\20\4\0\17\20\1\205\22\20"+
    "\55\0\1\206\21\0\1\20\4\0\40\20\1\207\1\20"+
    "\14\0\1\20\4\0\36\20\1\210\3\20\14\0\1\20"+
    "\4\0\34\20\1\211\5\20\14\0\1\20\4\0\16\20"+
    "\1\212\23\20\14\0\1\20\4\0\37\20\1\212\2\20"+
    "\14\0\1\20\4\0\21\20\1\213\20\20\14\0\1\20"+
    "\4\0\24\20\1\214\15\20\14\0\1\20\4\0\15\20"+
    "\1\215\24\20\61\0\1\216\15\0\1\20\4\0\36\20"+
    "\1\217\3\20\14\0\1\20\4\0\21\20\1\220\20\20"+
    "\14\0\1\20\4\0\35\20\1\221\4\20\14\0\1\20"+
    "\4\0\1\222\41\20\57\0\1\223\17\0\1\20\4\0"+
    "\21\20\1\224\20\20\14\0\1\20\4\0\33\20\1\225"+
    "\6\20\14\0\1\20\4\0\16\20\1\226\23\20\42\0"+
    "\1\227\34\0\1\20\4\0\37\20\1\226\2\20\14\0"+
    "\1\20\4\0\21\20\1\230\20\20\60\0\1\231\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6171];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\6\11\1\1\2\11\17\1\1\11"+
    "\1\0\21\1\1\11\27\1\1\0\17\1\1\0\5\1"+
    "\1\0\17\1\1\0\13\1\1\0\13\1\1\0\7\1"+
    "\1\0\4\1\1\0\3\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
public String errlex="";
public ArrayList<Token> ts = new ArrayList<Token>();
public Symbol symbol(int type){
return new Symbol(type,yyline,yycolumn);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errlex+="\nError lexico: " + yytext() + " caracter no valido en pos: " + (yyline+1) + "," + (yycolumn+1);
            }
            // fall through
          case 34: break;
          case 2:
            { 
            }
            // fall through
          case 35: break;
          case 3:
            { ts.add(new Token("comilla ", yytext()));return symbol(sym.comilla);
            }
            // fall through
          case 36: break;
          case 4:
            { ts.add(new Token("operador logico ", yytext()));return symbol(sym.ol);
            }
            // fall through
          case 37: break;
          case 5:
            { ts.add(new Token("P. Izquierdo ", yytext()));return symbol(sym.pi);
            }
            // fall through
          case 38: break;
          case 6:
            { ts.add(new Token("P. Derecho ", yytext()));return symbol(sym.pd);
            }
            // fall through
          case 39: break;
          case 7:
            { ts.add(new Token("operador aritmético ", yytext()));return symbol(sym.op);
            }
            // fall through
          case 40: break;
          case 8:
            { ts.add(new Token("coma ", yytext()));return symbol(sym.c);
            }
            // fall through
          case 41: break;
          case 9:
            { ts.add(new Token("Numero ", yytext()));return symbol(sym.num);
            }
            // fall through
          case 42: break;
          case 10:
            { ts.add(new Token("Puntos ", yytext()));return symbol(sym.puntos);
            }
            // fall through
          case 43: break;
          case 11:
            { ts.add(new Token("punto y coma ", yytext()));return symbol(sym.pc);
            }
            // fall through
          case 44: break;
          case 12:
            { ts.add(new Token("Op. relacional ", yytext()));return symbol(sym.or);
            }
            // fall through
          case 45: break;
          case 13:
            { ts.add(new Token("Asignación ", yytext()));return symbol(sym.asig);
            }
            // fall through
          case 46: break;
          case 14:
            { ts.add(new Token("Identificador ", yytext()));return symbol(sym.id);
            }
            // fall through
          case 47: break;
          case 15:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.si);
            }
            // fall through
          case 48: break;
          case 16:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.leer);
            }
            // fall through
          case 49: break;
          case 17:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.para);
            }
            // fall through
          case 50: break;
          case 18:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.paso);
            }
            // fall through
          case 51: break;
          case 19:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.tipo);
            }
            // fall through
          case 52: break;
          case 20:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.sino);
            }
            // fall through
          case 53: break;
          case 21:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.finsi);
            }
            // fall through
          case 54: break;
          case 22:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.hacer);
            }
            // fall through
          case 55: break;
          case 23:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.hasta);
            }
            // fall through
          case 56: break;
          case 24:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.segun);
            }
            // fall through
          case 57: break;
          case 25:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.finpara);
            }
            // fall through
          case 58: break;
          case 26:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.entonces);
            }
            // fall through
          case 59: break;
          case 27:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.escribir);
            }
            // fall through
          case 60: break;
          case 28:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.finsegun);
            }
            // fall through
          case 61: break;
          case 29:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.mientras);
            }
            // fall through
          case 62: break;
          case 30:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.inicio);
            }
            // fall through
          case 63: break;
          case 31:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.deotromodo);
            }
            // fall through
          case 64: break;
          case 32:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.finmientras);
            }
            // fall through
          case 65: break;
          case 33:
            { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.fin);
            }
            // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
