
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 26 09:32:13 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 3;
  public static final int or = 7;
  public static final int EOF = 0;
  public static final int pi = 4;
  public static final int num = 2;
  public static final int op = 8;
  public static final int error = 1;
  public static final int ol = 6;
  public static final int pd = 5;
}

