
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 26 23:47:07 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pc = 13;
  public static final int comilla = 20;
  public static final int tipo = 14;
  public static final int mientras = 9;
  public static final int hacer = 10;
  public static final int num = 2;
  public static final int or = 7;
  public static final int op = 8;
  public static final int ol = 6;
  public static final int inicio = 16;
  public static final int EOF = 0;
  public static final int asig = 12;
  public static final int id = 3;
  public static final int escribir = 18;
  public static final int error = 1;
  public static final int finmientras = 11;
  public static final int fin = 17;
  public static final int c = 15;
  public static final int pi = 4;
  public static final int leer = 19;
  public static final int pd = 5;
}

